displayName: Rewrite Header
summary: Extract data from the HTTP request header via regexp and add extracted data to a new.
type: middleware
import: github.com/mrdrelar/traefik-plugin-rewriteheader
compatibility: TODO
testData:
  fromhead: "X-TargetHeader"
  regex:    "foo.?"
  create:   "X-NewHeader"
  prefix:   "CN="

